valor = int(input("Digite o valor a ser sacado (entre 10 e 600): "))
if (
    valor < 10 or valor > 600
): 
    print("Valor inválido!")
else:
    cem = valor // 100  
    valor -= cem * 100 
    cinquenta = valor // 50 
    valor -= cinquenta * 50
    dez = valor // 10
    valor -= dez * 10
    cinco = valor // 5
    valor -= cinco * 5
    um = valor 
    if cem > 0:
        print("{} nota(s) de cem".format(cem))
    if cinquenta > 0:
        print("{} nota(s) de cinquenta".format(cinquenta))
    if dez > 0:
        print("{} nota(s) de dez".format(dez))
    if cinco > 0:
        print("{} nota(s) de cinco".format(cinco))
    if um > 0:
        print("{} nota(s) de um".format(um))